### ISSUE TITLE
Credentials in repo

### ISSUE THREAD

**Issue by jangraefen** [tech-otaku/hetzner-cloud-init#1]
Not sure if this is on purpose or not, but I just found your repository while using Google and could not help to notice that you have commited password hashes and a private key.

I thought I notify you, just in case these are real credentials.

Have a great day :)

**Comment by tech-otaku** [comment]
Jan,

Both the encrypted password and SSH keys are dummies, but thanks for taking the time to bring it to my attention.

Steve

**Comment by jangraefen** [comment]
👍
